name: amber

on:
  workflow_dispatch:

jobs:
  amber-build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        aiida-core: [2.6.1, 2.6.2, 2.6.3]
        ambertools: [24.8]
        python: [3.11]
    name: py${{ matrix.python }}-aiida${{ matrix.aiida-core }}-ambertools${{ matrix.ambertools }}
    steps:
 
      - name: prepare tag
        id: date
        run: |
            echo "tag=$(date +'%Y-%m-%d')-py${{ matrix.python }}-aiida${{ matrix.aiida-core }}-ambertools${{ matrix.ambertools }}" >> $GITHUB_OUTPUT

      - name: checkout
        uses: actions/checkout@v6.0.2

      - name: Authenticate with GHCR
        uses: docker/login-action@v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.BUILD_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.12.0

      - name: Build and push
        uses: docker/build-push-action@v6.18.0
        with:
          file: ./amber/Dockerfile
          build-args: |
            AIIDAVERSION=${{ matrix.aiida-core }}
            AMBERTOOLSVERSION=${{ matrix.ambertools }}
            PYTHONVERSION=${{ matrix.python }}
          tags: ghcr.io/${{ vars.ORG_REPO }}/aiida-amber-testenv:${{ steps.date.outputs.tag }}
          push: true
