name: gromacs

on:
  workflow_dispatch:

jobs:
  gromacs-build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        gromacs: [2025.4]
        plumed: [2.9.2]
    name: gromacs${{ matrix.gromacs }}-plumed${{ matrix.plumed }}
    steps:

      - name: prepare tag
        id: date
        run: |
            echo "tag=$(date +'%Y-%m-%d')-gromacs${{ matrix.gromacs }}-plumed${{ matrix.plumed }}" >> $GITHUB_OUTPUT

      - name: checkout
        uses: actions/checkout@v6.0.2

      - name: Authenticate with GHCR
        uses: docker/login-action@v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.BUILD_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.12.0

      - name: Build and push
        uses: docker/build-push-action@v6.18.0
        with:
          file: ./gromacs/Dockerfile
          build-args: |
            GMXVERSION=${{ matrix.gromacs }}
            PLUMEDVERSION=${{ matrix.plumed }}
          tags: ghcr.io/${{ vars.ORG_REPO }}/aiida-gromacs-testenv:${{ steps.date.outputs.tag }}
          push: true
